#!/bin/dash
#Gets the commit number.
CommitNum=0
for file in .pig/commits/*
do
    if [ -d "$file" ]
    then
        CommitNum=$((CommitNum + 1))
    fi
done


# -a option enabled
if [ "$#" -eq 3 ]
then
    for file in .pig/index/*
    do
        FileName="$(echo "$file" | cut -d'/' -f3)"
        for CurrFile in *
        do
            if [ "$CurrFile" = "$FileName" ]
            then
                cp "$CurrFile" .pig/index/
            fi
        done
    done
fi


#check if files to be commited have been changed compared to previous commits.
if [ "$#" -eq 2 ]
then
    if ! ls -A1q .pig/tmpIndex | grep -q .
    then
        echo "nothing to commit" 1>&2
        exit 1
    fi
fi

for file in .pig/tmpIndex/*
do
    if ls -A1q .pig/tmpIndex | grep -q .
    then
        commitdif.sh "$file"
        if [ $? -eq 1 ] 
        then
            echo "nothing to commit" 1>&2
            exit 1
        fi
            mv "$file" .pig/index 
    fi
done


#Create new directory with name, CommitNum
mkdir .pig/commits/"$CommitNum"

#copies files from index to new dir
for file in .pig/index/*
do
    cp "$file" .pig/commits/"$CommitNum"
done

#create new file inside dir for message
echo "$2" > .pig/commits/"$CommitNum"/message.txt
echo "Committed as commit $CommitNum"