#!/bin/dash

for dir in .pig/commits/*
do
    # echo $dir
    CommitNum="$(echo $dir | cut -d'/' -f3)"
    CommitMsg="$(cat .pig/commits/$CommitNum/message.txt)"
    echo "$CommitNum $CommitMsg" >> tmp.txt
done
sort -rnk1 tmp.txt
rm tmp.txt