#!/bin/dash
#Gets the commit number.
CommitNum=0
for file in .pig/commits/*
do
    if [ -d "$file" ]
    then
        CommitNum=$((CommitNum + 1))
    fi
done

#check if change was made to files

#Create new directory with name, CommitNum
mkdir .pig/commits/"$CommitNum"

for file in .pig/index/*
do
    .commitdif.sh "$file"
    if [ $? -eq 1 ] 
    then
        echo "nothing to commit" 1>&2
        rm -r .pig/commits/"$CommitNum"
        exit 1
    fi 
done
#move files from index to new dir

for file in .pig/index/*
do
    mv "$file" .pig/commits/"$CommitNum"
done

#create new file inside dir for message

echo "$2" > .pig/commits/"$CommitNum"/message.txt
echo "Committed as commit $CommitNum"