#!/bin/dash
# Gets the commit num and file name into variables
CommitNum="$(echo $1 | cut -d\: -f1)"
FileName="$(echo $1 | cut -d\: -f2)"

#If commit Number is ommited 
if [ -z "$CommitNum" ]
then
    for file in .pig/index/*
    do
        fileCutName="$(echo $file | cut -d'/' -f3)"   
        if [ "$fileCutName" = "$FileName" ]
        then
            cat "$file"
            exit 0
        fi
    done
    echo "error: '$FileName' not found in index" 1>&2
    exit 1
fi

#Commit Num is included
for dir in .pig/commits/*
do
    dirNum="$(echo $dir | cut -d'/' -f3)"
    if [ "$dirNum" = "$CommitNum" ]
    then
        ShowFile=.pig/commits/"$CommitNum"/"$FileName"
        if [ ! -f  "$ShowFile" ]
        then
            echo "error: $FileName not found in commit $CommitNum" 1>&2
            exit 1
        fi
        cat .pig/commits/$CommitNum/$FileName
        exit 0
    fi
    echo "error: unknown commit '$CommitNum'" 1>&2
    exit 1
done