#!/bin/dash
#Test if .pig already exists
if test -d .pig 
then
    echo "$0: error: .pig already exists" 1>&2
    exit 1
fi

mkdir .pig
mkdir .pig/index
mkdir .pig/commits
echo "Initialized empty pigs repository in .pig"
